
services:
  nginx:
    image: nginx:latest
    container_name: soc_nginx
    ports:
      - "8080:80"
    volumes:
      - './logs:/var/log/nginx'
    networks:
      - soc_net
  soc:
    build: .
    container_name: soc
    volumes:
      - './logs:/logs'
      - './soc_container:/app'
    networks: 
      - soc_net

networks:
  soc_net:
    driver: bridge
