
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - './logs:/var/log/nginx'
    networks:
      - soc_net
      
  blue:
    build: ./blue
    container_name: blue
    volumes:
      - './logs:/logs'
      - './blue:/app'
    networks: 
      - soc_net
    environment:
      - TARGET=http://nginx:80

  red:
    container_name: red
    build: ./red
    volumes:
      - './red:/app'
    networks:
      - soc_net
    environment:
      - TARGET=http://nginx:80


networks:
  soc_net:
    driver: bridge
